version: "3.3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

    depends_on:
      - app

    links:
      - app

    restart: unless-stopped

    volumes:
      - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/etc/vhosts.d/:/etc/nginx/vhosts.d
      - ./app:/var/www/html
      - ./docker/nginx/etc/conf.d:/etc/nginx/conf.d


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: test
      MYSQL_USER: test
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db-extra/:/docker-entrypoint-initdb.d/:rw
      - ./db_data:/var/lib/mysql:rw

  app:
    build:
      context: ./php
    depends_on:
      - db
    working_dir: /var/www/html/site
    volumes:
      - ./app/:/var/www/html
      - ./php/etc/php.ini:/usr/local/etc/php/conf.d/99-custom.ini


#volumes:
#  db_data: {}
